### ISSUE TITLE
질문사항

### ISSUE THREAD

**Issue by chansooo** [GongGanGam/GongGanGam-Server#18]
## 질문
1. 푸시알림은 어떻게 되어가고 있나요?
2. 푸시알림 통해서 지정된 시각(현재는 메소드를 불렀을 때라고 생각)에 랜덤으로 일기를 전달해주는 로직이 구성되어 있나요?

**Comment by gimangi** [comment]
로그인할 때 헤더로 apple/android 구분해서 APNs/FCM으로 구현할 예정입니다.
1. 현재 APNs 인증 및 전송 로직 구현되어 있습니다.
2. 21시에 공유허용으로 작성된 일기들을 활성 사용자에게 공유하고, 푸시를 보내도록 구현 중입니다.
