### ISSUE TITLE
[FIX] 일기 상세 response 변경

### ISSUE THREAD

**Issue by chansooo** [GongGanGam/GongGanGam-Server#27]
##  ✅ 할일
- [x] 해당 일기에 답장이 있다면 해당 답장 ID를 함께 보내주거나, 답장까지 한 번에 보내주기.
->
- [x] DiaryDTO에 replyId 추가
- [x] 상세 일기 fetch 할 때 reply 같이 내려주기? 이건 한번 다시 봐야할 듯

**Comment by gimangi** [comment]
- [x] [추가] 일기 월별 response에서 detail 추가
